### ISSUE TITLE
Question:where is extract-btf-aarch64.rs came from

### ISSUE THREAD

**Issue by kevi-sun** [foniod/build-images#8]
There is extract-btf-aarch64.rs used in both Dockerfile of ubuntu21.04 and fedora35, anyone know how it is generated

**Comment by rhdxmr** [comment]
Hello this is the author you were looking for :smile: 

In the Linux kernel source tree, there is `extract-vmlinux` script that extracts `vmlinux` from the `vmlinuz`, the compressed kernel image. I found that it works on x86-64 correctly but it does not work on AMD64 architecture.
 

Since RedBPF can make use of `vmlinux` to load kernel BTF info from it, the Dockerfiles run `extract-vmlinux` on x86-64 architecture.
Also RedBPF can load BTF info from the raw BTF data, so the Dockerfiles run `extract-btf-aarch64` on AMD64 architecture.

I admit that `extract-btf-aarch64.rs` is not generic since it is based on the pattern of the `btf_header` structure. It is not great but just works for now.
